// <auto-generated />
using System;
using Lib.EF.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lib.EF.Migrations
{
    [DbContext(typeof(EmpresaDBContext))]
    [Migration("20250206175616_projectes")]
    partial class projectes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmpleatProjecte", b =>
                {
                    b.Property<int>("EmpleatsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectesId")
                        .HasColumnType("int");

                    b.HasKey("EmpleatsId", "ProjectesId");

                    b.HasIndex("ProjectesId");

                    b.ToTable("EmpleatProjecte");
                });

            modelBuilder.Entity("Lib.Model.Model.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Departaments");
                });

            modelBuilder.Entity("Lib.Model.Model.Empleat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNaix")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Salari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Empleats");
                });

            modelBuilder.Entity("Lib.Model.Model.Projecte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projectes");
                });

            modelBuilder.Entity("EmpleatProjecte", b =>
                {
                    b.HasOne("Lib.Model.Model.Empleat", null)
                        .WithMany()
                        .HasForeignKey("EmpleatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib.Model.Model.Projecte", null)
                        .WithMany()
                        .HasForeignKey("ProjectesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lib.Model.Model.Empleat", b =>
                {
                    b.HasOne("Lib.Model.Model.Departament", "Dept")
                        .WithMany("Empleats")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("Lib.Model.Model.Departament", b =>
                {
                    b.Navigation("Empleats");
                });
#pragma warning restore 612, 618
        }
    }
}
